CREATE TABLE IF NOT EXISTS components
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    type        INTEGER,
    description VARCHAR(255),
    cost        INTEGER,
    image       VARCHAR(255),
    CONSTRAINT pk_components PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    role     INTEGER,
    password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);